import { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, LogOut, ShieldCheck, Signal } from 'lucide-react';
import type { User } from '@supabase/supabase-js';
import LiveStatusPanel from '../components/LiveStatusPanel';
import TrendGraph from '../components/TrendGraph';
import EventTimeline from '../components/EventTimeline';
import { MonitoringData, Event, DataPoint } from '../types/monitoring';
import { detectEvents, createDataPoint, parseCSVLine } from '../utils/dataProcessor';
import { supabase } from '../utils/supabaseClient';

interface DashboardProps {
  user: User;
}

const stateBadgeStyles: Record<MonitoringData['state'], string> = {
  NORMAL: 'bg-green-600 text-white',
  SHIFT: 'bg-yellow-500 text-slate-900',
  ALERT: 'bg-red-600 text-white',
  RECOVERY: 'bg-blue-600 text-white',
};

const stateLabels: Record<MonitoringData['state'], string> = {
  NORMAL: 'NORMAL',
  SHIFT: 'PHYSIOLOGICAL SHIFT',
  ALERT: 'ALERT – Hypoglycemia Risk',
  RECOVERY: 'RECOVERY',
};

export default function Dashboard({ user }: DashboardProps) {
  const [currentData, setCurrentData] = useState<MonitoringData | null>(null);
  const [hrData, setHrData] = useState<DataPoint[]>([]);
  const [tempData, setTempData] = useState<DataPoint[]>([]);
  const [sweatData, setSweatData] = useState<DataPoint[]>([]);
  const [events, setEvents] = useState<Event[]>([]);
  const [isConnected, setIsConnected] = useState(false);
  const [emailStatus, setEmailStatus] = useState<string | null>(null);

  const previousDataRef = useRef<MonitoringData | null>(null);
  const lastAlertSentRef = useRef<number | null>(null);

  const patientName = useMemo(() => {
    return (user.user_metadata?.full_name as string | undefined) || user.email || 'Patient';
  }, [user]);

  const deviceId = import.meta.env.VITE_DEVICE_ID || 'ESP32-EDGE-001';

  const sendAlertEmail = async (payload: MonitoringData, detectedEvents: Event[]) => {
    if (!user.email) return;

    const now = new Date();
    const alertData = {
      to: user.email,
      timestamp: now.toISOString(),
      state: payload.state,
      heart_rate: payload.heart_rate,
      skin_temp: payload.skin_temp,
      sweat_level: payload.sweat_level,
      events: detectedEvents.map((event) => event.message),
      disclaimer: 'This alert is generated by a research dashboard and is not a medical diagnosis.',
    };

    const { error } = await supabase.functions.invoke('send-alert-email', {
      body: alertData,
    });

    if (error) {
      setEmailStatus('Alert email failed to send.');
    } else {
      setEmailStatus('Alert email sent.');
    }
  };

  useEffect(() => {
    const wsUrl = import.meta.env.VITE_ESP32_WS_URL as string | undefined;

    if (!wsUrl) {
      setIsConnected(false);
      return;
    }

    let socket: WebSocket | null = null;
    let reconnectTimer: number | null = null;

    const connect = () => {
      socket = new WebSocket(wsUrl);

      socket.onopen = () => {
        setIsConnected(true);
      };

      socket.onclose = () => {
        setIsConnected(false);
        if (reconnectTimer === null) {
          reconnectTimer = window.setTimeout(() => {
            reconnectTimer = null;
            connect();
          }, 2000);
        }
      };

      socket.onerror = () => {
        setIsConnected(false);
      };

      socket.onmessage = (event) => {
        const parsed = parseCSVLine(String(event.data));
        if (!parsed) return;

        const prev = previousDataRef.current;
        const newEvents = detectEvents(parsed, prev);

        if (newEvents.length > 0) {
          setEvents((prevEvents) => [...newEvents, ...prevEvents].slice(0, 50));
        }

        setCurrentData(parsed);
        setHrData((prevData) => [...prevData, createDataPoint(parsed, 'hr')].slice(-100));
        setTempData((prevData) => [...prevData, createDataPoint(parsed, 'temp')].slice(-100));
        setSweatData((prevData) => [...prevData, createDataPoint(parsed, 'sweat')].slice(-100));

        if (parsed.state === 'ALERT' && prev?.state !== 'ALERT') {
          const now = Date.now();
          if (!lastAlertSentRef.current || now - lastAlertSentRef.current > 60_000) {
            lastAlertSentRef.current = now;
            void sendAlertEmail(parsed, newEvents);
          }
        }

        previousDataRef.current = parsed;
      };
    };

    connect();

    return () => {
      if (reconnectTimer !== null) {
        window.clearTimeout(reconnectTimer);
      }
      if (socket) {
        socket.close();
      }
      setIsConnected(false);
    };
  }, []);

  const currentState = currentData?.state || 'NORMAL';

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
      <header className="bg-white shadow-md border-b-4 border-slate-900">
        <div className="max-w-7xl mx-auto px-6 py-6">
          <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
            <div className="flex items-center gap-3">
              <Activity className="w-10 h-10 text-slate-900" strokeWidth={2.5} />
              <div>
                <h1 className="text-3xl font-bold text-slate-900 tracking-tight">
                  VITALSHIFT
                </h1>
                <p className="text-sm text-slate-600 font-medium">Real-Time Physiological Monitoring</p>
              </div>
            </div>
            <div className="flex flex-wrap items-center gap-3">
              <div className="flex items-center gap-2 bg-slate-900 text-white px-4 py-2 rounded-full text-sm font-semibold">
                <Signal className="w-4 h-4" />
                {isConnected ? 'ESP32 Connected' : 'Disconnected'}
              </div>
              <button
                onClick={() => supabase.auth.signOut()}
                className="flex items-center gap-2 text-sm font-semibold text-slate-700 hover:text-slate-900"
              >
                <LogOut className="w-4 h-4" />
                Sign out
              </button>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-6 py-8">
        <div className="space-y-8">
          <section className="bg-white rounded-lg shadow-lg p-6">
            <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
              <div>
                <p className="text-sm uppercase tracking-wide text-slate-500">Patient Overview</p>
                <h2 className="text-2xl font-bold text-slate-900 mt-1">{patientName}</h2>
                <div className="mt-2 flex flex-wrap items-center gap-3 text-sm text-slate-600">
                  <span>Device ID: {deviceId}</span>
                  <span className={`inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-semibold ${isConnected ? 'bg-emerald-100 text-emerald-700' : 'bg-red-100 text-red-700'}`}>
                    <span className={`w-2 h-2 rounded-full ${isConnected ? 'bg-emerald-500' : 'bg-red-500'}`}></span>
                    {isConnected ? 'Wearable Online' : 'Wearable Offline'}
                  </span>
                </div>
              </div>
              <div className="flex flex-col gap-2">
                <span className={`inline-flex items-center gap-2 px-4 py-2 rounded-full font-semibold ${stateBadgeStyles[currentState]}`}>
                  <ShieldCheck className="w-4 h-4" />
                  {stateLabels[currentState]}
                </span>
                <span className="text-xs text-slate-500">System state updated in real time</span>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4 flex items-center gap-2">
              <div className="w-1 h-6 bg-slate-900"></div>
              Live Physiological Metrics
            </h2>
            <LiveStatusPanel data={currentData} />
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4 flex items-center gap-2">
              <div className="w-1 h-6 bg-slate-900"></div>
              Trend Visualization
            </h2>
            <div className="grid grid-cols-1 gap-6">
              <TrendGraph
                title="Heart Rate vs Time"
                data={hrData}
                unit="BPM"
                color="#ef4444"
              />
              <TrendGraph
                title="Skin Temperature vs Time"
                data={tempData}
                unit="°C"
                color="#f97316"
              />
              <TrendGraph
                title="Sweat Level vs Time"
                data={sweatData}
                unit="Conductivity"
                color="#3b82f6"
              />
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4 flex items-center gap-2">
              <div className="w-1 h-6 bg-slate-900"></div>
              Explainability Event Timeline
            </h2>
            <EventTimeline events={events} />
          </section>

          <section className="bg-white rounded-lg shadow-lg p-6">
            <h3 className="text-lg font-semibold text-slate-800">Alert & Notification System</h3>
            <p className="text-sm text-slate-600 mt-2">
              When the system enters the ALERT state, an email notification is sent to the logged-in user via Supabase SMTP.
            </p>
            <div className="mt-3 text-sm text-slate-700">
              Status: {emailStatus || 'Standing by'}
            </div>
            <p className="mt-3 text-xs text-slate-500">
              Safety disclaimer: This system does not provide medical diagnosis. It visualizes physiological response patterns associated with hypoglycemia risk.
            </p>
          </section>
        </div>
      </main>

      <footer className="bg-white border-t border-slate-200 mt-12">
        <div className="max-w-7xl mx-auto px-6 py-6 text-center text-sm text-slate-600">
          <p className="font-medium">VITALSHIFT Edge Intelligence System</p>
          <p className="text-slate-500 mt-1">
            Demonstrating personalized baselines and explainable system behavior
          </p>
        </div>
      </footer>
    </div>
  );
}
